apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: LoadBalancer
  selector:
    app: autoscaling-server-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
