apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: autoscaling-server-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
